services:
  mongo:
    image: mongo:6
    container_name: cookmate_mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: cookmate_redis
    ports:
      - "6379:6379"

  chroma:
    image: chromadb/chroma
    container_name: cookmate_chroma
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8
    container_name: cookmate_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookmate
      MYSQL_USER: cookmate
      MYSQL_PASSWORD: cookmate
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
